### PR TITLE
Add IPv6 support to NFLOG

### PR DESCRIPTION
**Pull request by NeroProtagonist**
As in title, Nflog can now decode and print IPv6 + TCP/UDP/ICMPv6 packets.
Also updated all builds to use API 21 (latest available on NDK10).

Tested on Pixel 4a (arm architecture).
Compiled binaries for the other platforms but can't test them.

### CODE REVIEW

**Comment by NeroProtagonist** [comment]
Fixes #1232

**Review by ukanth — COMMENTED** [review]
Looks good.

**Review by ukanth — APPROVED** [review]

**Comment by bsdice** [comment]
After xz backdooring, uploading binaries to a repo is seriously bad practice, imho.

Why is the x86 binary 4k bigger and the others only bytes?

**Comment by ukanth** [comment]
> After xz backdooring, uploading binaries to a repo is seriously bad practice, imho.
> 
> Why is the x86 binary 4k bigger and the others only bytes?

I usually compile all the binaries from source and bundle it before releasing it to public.

**Comment by yashikada** [comment]
> Why is the x86 binary 4k bigger and the others only bytes?

this happens because the arm architecture is more optimized than the x86 one, there are fewer instructions to do the same thing.
However you are absolutely right.

> I usually compile all the binaries from source and bundle it 

but this did not happen in this case. Are we sure that the author of this PR is reliable?
Wouldn't it be to have all the binaries compiled with github actions?

**Comment by linsui** [comment]
How is this built with api 21? Wait3 is not available in api 21 and the busybox build is fixed in 1.34.0 in https://github.com/mirror/busybox/commit/c0943ac451051b734711b0c95731ae7c515dbb31.

**Pull request merged**
