### PR TITLE
Add Fingerprint protection

### PR DESCRIPTION
**Pull request by vzool**
Hi...

I have added this feature for Marshmallow or newer versions of Android and I've tested in some different environments:
- OnePlus 3 (6.0.1) official Rooted ROM.
- Galaxy Note II(4.4.4) custom ROM by **Cyngenmod**.
- Galaxy Note 3(4.4.4) in Emulator by **Genymotion**.

I'm not sure if this right place to pull this request in **stable** branch, because I don't see any instructions about which pull requests should goes to which branch in [contribution section](https://github.com/ukanth/afwall#contributing).

I think that I can change the same pull request into different branch, so tell me if you want that.

Hope you like it, Thanks

alt tag

### CODE REVIEW

**Comment by ukanth** [comment]
@vzool , Thanks for the PR. Yes, Pull request has to be with BETA branch. I will update that in the documentation. I will go through the changes when I get some time.

Couple of points

1. strings.xml changes are only required for english. Other languages are managed by crowdin. So, please revert the changes in other languages files.
2. What happens when device doesn't support Fingerprint ? In that case option should not be available

Thanks.

**Comment by vzool** [comment]
@ukanth You welcome...

Ok, I changed pull request into **beta** branch and I will revert languages and resolve the conflicts when I get home. Current behaviour for fingerprint in unsupported devices will be shown and user can select it, but the selection will not be reflected into settings and app will replay to user by `Api.Toast` that your device does not have a fingerprint.

As you say, if fingerprint option hidden when device not support will be better, but I don't know how to do it yesterday. I'll dig more and try to do my best, I will notify you when I can't. :)

In addition, I used Custom [Dialog](https://developer.android.com/guide/topics/ui/dialogs.html) which are not very good for fingerprint operation as I think, because I can't drive lifecycle from End-to-End, [DialogFragment](https://developer.android.com/reference/android/app/DialogFragment.html) is better option for my objective check this:

> ### Lifecycle
> DialogFragment does various things to keep the fragment's lifecycle driving it, instead of the Dialog. Note that dialogs are generally autonomous entities -- they are their own window, receiving their own input events, and often deciding on their own when to disappear (by receiving a back key event or the user clicking on a button).
> DialogFragment needs to ensure that what is happening with the Fragment and Dialog states remains consistent.

Even so, I can't catch "Home Button press Event" in  [Dialog](https://developer.android.com/guide/topics/ui/dialogs.html), it was completely removed from Android M due to protect users from misbehaver apps (I do support this direction).
I will change to [DialogFragment](https://developer.android.com/reference/android/app/DialogFragment.html), it will makes me predict user behaviour in app while listening and wait for fingertip.

Thanks for your replay

**Comment by vzool** [comment]
@ukanth still needs some functionality enhancements. :)
By the way, why we keep track changes for this file ` aFWall/aFWall.iml `?
I noticed that it always has the same output with different order!
Thanks

**Comment by ukanth** [comment]
You can ignore that changes, it's handled by AndroidStudio. I'll add it to .gitignore. I'll review the changes over the weekend.

**Comment by ukanth** [comment]
@vzool , Have you merged the changes from beta to stable on this Pull request ? I see my changes also included as part of the code changes and it's very confusing. Could you please do a clean PR with only the changes done for Fingerprint ?

**Comment by vzool** [comment]
@ukanth Of course, no problem at all, sorry for that.
To clarify to you what I did before, first I made a new branch [FingerprintProtection-feature](https://github.com/vzool/afwall/tree/FingerprintProtection-feature) from [stable](https://github.com/ukanth/afwall/tree/stable) and then I merged [beta](https://github.com/ukanth/afwall/tree/beta) into [FingerprintProtection-feature](https://github.com/vzool/afwall/tree/FingerprintProtection-feature).

This application is very sensitive and required a precision, so we should try do anything as clean as possible.
I think that I will close this pull request and create a new branch from beta and start over again.

Thanks

**Pull request closed without merging**
