### PR TITLE
Refresh screenshot on readme

### PR DESCRIPTION
**Pull request by Magissia**
Replace old screenshot by screenshot from the latest version of AFwall to reflect GUI change that was made, based on Play Store's provided screenshot

### CODE REVIEW

**Comment by CHEF-KOCH** [comment]
Seems to not work (link down or something). Please upload the screenshots on a proper place or just post it here so that I can upload it on a proper place like on my imgur account. 

<code>https://lh3.googleusercontent.com/W2fTgB1Ho52F5iK7GYWknd1B-mCCLeEHJYK4xviWxQSo63haZmYoWehJ8kbwwMyi3a4=h900-rw</code> points me to an unamed.webp file. This is a no-go.

**Comment by CHEF-KOCH** [comment]
Nvm, I [fixed it myself](https://github.com/ukanth/afwall/pull/434).

**Comment by Magissia** [comment]
Why was it merged if it doesn't work ?

Sigh

Will check when i'm on a computer

**Comment by CHEF-KOCH** [comment]
Maybe it worked for a short time, but so what it's fixed now.

**Pull request merged**
