### PR TITLE
Fix #650: Use root permissions to check if paths exist

### LINKED ISSUE #650: "Fix startup data leak" checkbox not available (magisk+)
If the "Fix startup data leak" checkbox is dimmed so that it cannot be enabled (checked), please reply to this issue so we can figure it out.

Please supply the AFWall+ version, Android version, `su` app, `su` app version, whether or not the Xposed Framework is installed, and whether or not AFWall+ is enabled in Xposed.  Here is a template:

**AFWall+ version:** 2.9.1
**Android version:** KitKat
**su:** SuperSU by chainfire
**su version:** 2.79
**Xposed installed:** Yes
**AFWall+ enabled in Xposed:** Yes

### PR DESCRIPTION
**Pull request by ljani**
For example the paths used with Magisk are not accessible by normal users. This
commit fixes the issue by using root permissions to test the paths.

Those paths are not accessible by normal users, because for example they contain
apps' private data, or Magisk is trying to hide itself from detection.

### CODE REVIEW

**Comment by ljani** [comment]
@ukanth I'm a little inexperienced with working with root permissions on Android. Is it okay to call `RootTools` directly, or should those calls be wrapped in a thread, like you've done in the methods?

**Comment by ljani** [comment]
Here's also a repro:

```sh
afwall ❯❯❯ adb shell
OnePlus6T:/ $ ls /data/adb/service.d
ls: /data/adb/service.d: Permission denied
OnePlus6T:/ $ su
OnePlus6T:/ # ls /data/adb/service.d
afwallstart
```

**Comment by ljani** [comment]
Ah, are those threads there, because root commands are a little slow to execute?

**Comment by ukanth** [comment]
Thanks for PR. Usually root command executed not on Main UI thread for various reasons. Yes. it needs to run in separate thread.

**Comment by ljani** [comment]
Okay, I'll do a little refactoring as well when I have a chance.

For others, I found [a little guidance](https://su.chainfire.eu/#when-not) I should have read before the PR. In summary, it seems root calls should not be done on the main thread for the same reasons you shouldn't be doing i/o on the main thread.

**Comment by ljani** [comment]
Okay, I'm now using fire-and-forget threads similar to the other methods.

**Pull request merged**
