### PR TITLE
About.html update to fix #443

### LINKED ISSUE #443: 'About' box links not working
I'm not sure which version - 'About' & 'app backup & restore' report V2.1.1 but 'Play Store' reports V2.1.2 

The green links in the 'menu>Help>About' page do nothing.

### PR DESCRIPTION
**Pull request by CHEF-KOCH**
Fix links are not working

### CODE REVIEW

**Comment by CHEF-KOCH** [comment]
Someone without emulator must test this to ensure it's working, I only can test this over [here](http://www.w3schools.com/html/tryit.asp?filename=tryhtml_intro).

**Comment by ukanth** [comment]
This has nothing to do with html. There was a bug in AboutFragment. I've fixed it. Thanks.

**Comment by CHEF-KOCH** [comment]
Okay, I didn't know you changed that. Than all is okay how it is. :+1:

**Comment by ukanth** [comment]
Added you in credits section and you deserve it :)

**Pull request closed without merging**
