### PR TITLE
Added localnet multicast-adresses to wifi-lan chain

### PR DESCRIPTION
**Pull request by ionum**
224.0.0.0/24 and ffx2::/16 belong to the local net....

### CODE REVIEW

**Review by Gitoffthelawn — CHANGES_REQUESTED** [review]
You need a closing parenthesis in the second line you added.

**Comment by ukanth** [comment]
@ionum , Please fix the syntax error. I have some other ideas to implement these special rules without actually touching the main code.

**Comment by ionum** [comment]
Any news on this issue?

**Comment by ukanth** [comment]
@ionum Can you resolve the conflicts, I might accept the PR till I have the new solution in place.

**Comment by ionum** [comment]
@ukanth Done

**Pull request merged**
