### PR TITLE
Do not break old SU apps

### PR DESCRIPTION
**Pull request by CHEF-KOCH**
* Versions bump, we are in 2015 now, old stuff removed 
* Do not break old su apps
* Bump final SDK 22 version in order to make it work on Android M

### CODE REVIEW

**Comment by ukanth** [comment]
@CHEF-KOCH, I guess we no longer need SUPER_USER permission.

**Comment by CHEF-KOCH** [comment]
We need it in order to not break older su apps, chainfie only remove this because his su version does not need it, all other apps needs it hardly.

**Comment by ukanth** [comment]
What do you mean by "all other apps" ? Other SU Apps ?

**Comment by CHEF-KOCH** [comment]
Yes of course, imho the only one that was updated to manage chainfires policy was the old CM app. All others still using them, this is also the reason F-Droid now reverted this, so it's not only a AFWall+ problem.

**Comment by ukanth** [comment]
Manually updated SUPERUSER permission back. Not updating sdk now

**Pull request closed without merging**
