### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by CHEF-KOCH**
Fix for c24a3ff3abb34eac24942684ed3093bf1d721f5d

### CODE REVIEW

**Comment by CHEF-KOCH** [comment]
If someone wants to play with the size:

Direct link
```
http://i.imgur.com/tLzXlqu.png
```

Markdown
```
[Imgur](http://i.imgur.com/tLzXlqu.png)
```

HTML
```
<a href="http://imgur.com/tLzXlqu"><img src="http://i.imgur.com/tLzXlqu.png" title="source: imgur.com" /></a>
```

BBCode
```
[img]http://i.imgur.com/tLzXlqu.png[/img]
```

Linked BBCode
```
[url=http://imgur.com/tLzXlqu][img]http://i.imgur.com/tLzXlqu.png[/img][/url]
```

**Comment by Magissia** [comment]
You have been quicker than me, thanks.

**Comment by ukanth** [comment]
I have uploaded screenshots to github as a separate folder since should not depend on imgur. Hence closing the issue.

**Comment by CHEF-KOCH** [comment]
Thanks ukanth. :+1:

**Pull request closed without merging**
