### PR TITLE
Potential fix for issue #709

### PR DESCRIPTION
**Pull request by peake**
ukanth,

After much investigating and debugging of my data leak problem, it looks like it's caused by a change in Android 7.x.  Network connectivity change broadcasts now need a broadcast receiver created in code, declaring a receiver in the manifest no longer works.  See [https://developer.android.com/reference/android/net/ConnectivityManager.html#CONNECTIVITY_ACTION](url).

My fix does this with a service, although I'm not 100% sure if we really need one dedicated just to this.  Please have a look.  This pull also includes a small bit of code cleanup in a related file.

Thanks, -Cal

### CODE REVIEW

**Comment by ukanth** [comment]
Thanks for the PR. I will check it today and get back. 

UPDATE:
The problem with this approach is, AFWall+ doesn't run in foreground and there is high chance it might get terminated.

Dirty solution would be downgrading the targetSdkversion to 23 for now

**Comment by peake** [comment]
I thought about that too, but the manifest says we're targetting 22.  Is the build environment not honoring that directive?

**Comment by ukanth** [comment]
It's driven out of build.gradle https://github.com/ukanth/afwall/blob/beta/aFWall/build.gradle#L12
not Manifest.

**Comment by peake** [comment]
Ah!  Well, hmm... I think there's some ways to make a service more resilient against the OOM killer.  Also, I think having the notification icon present adds towards that goal as well.  I'm willing to do a bit of research into it if you think it's worthwhile.

**Comment by ukanth** [comment]
Yes, surely. I'm already doing similar in LogService (STICKY).

**Comment by peake** [comment]
At one point I was returning STICKY, but I dropped it for some reason I can't recall off the top of my head.

Currently, if the main process gets killed, what guarantees it will get restarted?

**Comment by ukanth** [comment]
It won't guarantee, because we don't have foreground. one of the other way of doing this to call JobScheduler and check for the process.

only negative side might be higher battery usage.

**Comment by ukanth** [comment]
Are you working on introducing foreground process to handle this ? Let me know if any updates.

**Comment by ukanth** [comment]
Can you resubmit the PR ?

**Comment by bobham** [comment]
$idjdb

**Comment by ukanth** [comment]
Closed due to inactive.

**Pull request closed without merging**
