### PR TITLE
Create MuoBinAlshekh.SECURITY.md

### PR DESCRIPTION
**Pull request by MuoBinAlshekh**

### CODE REVIEW

**Comment by ukanth** [comment]
Could you tell me the purpose of this PR ?

**Comment by MuoBinAlshekh** [comment]
https://education.github.community/t/students-remove-stale-assignments/71977?u=muobinalshekh

**Comment by MuoBinAlshekh** [comment]
[]() [Muo](https://education.github.community/t/students-remove-stale-assignments/71977?u=muobinalshekh)

**Comment by MuoBinAlshekh** [comment]
https://education.github.community/t/students-remove-stale-assignments/71977?u=muobinalshekh

**Pull request closed without merging**
