### PR TITLE
Fix null pointer issue

### PR DESCRIPTION
**Pull request by vzool**
Hi,
While I'm discover and test the code, I found Null pointer exception.

Thanks

### CODE REVIEW

**Comment by ukanth** [comment]
It's actually explicit null. 

https://github.com/ukanth/afwall/blob/f376fc2a29e06f9018edd5d41a908c436be252a5/aFWall/src/main/java/dev/ukanth/ufirewall/log/LogService.java#L185

**Comment by vzool** [comment]
@ukanth ok, but it does report null exception while access its default value in beta version install.
Specially, when tab off/on for log services.
The problem occurs in [**G.java**](https://github.com/ukanth/afwall/blob/stable/aFWall/src/main/java/dev/ukanth/ufirewall/util/G.java#L341) when `G.logTarget()` called `isEmpty()`, and as I think `null` object doesn't have `isEmpty()` function and that what cause the issue.
Thanks

**Comment by ukanth** [comment]
@vzool , Do you have any steps to reproduce this ? I can check it.

**Comment by vzool** [comment]
@ukanth Yes, of course.
Make a fresh clean install from **beta** branch, then in the preferences tab on/off for log services many times, and the issue will appear to you.

**Comment by ukanth** [comment]
I have fixed using dcd24363a6b51907fa0078659d39f5fd9fb921ef, Thanks for pointing it out.

**Comment by vzool** [comment]
Thank you very much

**Pull request closed without merging**
