### PR TITLE
#876 Implement Bluetooth filtering

### PR DESCRIPTION
**Pull request by n90p**

### CODE REVIEW

**Comment by ukanth** [comment]
With all tethering, the problem is when to apply the rules. There is no reliable way to detect the change. How does we know the user is tethering it via bluetooth or usb ?

**Comment by n90p** [comment]
> With all tethering, the problem is when to apply the rules. There is no reliable way to detect the change.

What about `android.net.conn.TETHER_STATE_CHANGED`?

**Comment by ukanth** [comment]
All tethering is forwarding of IP addresses.We already have this implemented for any wifi tether. https://github.com/ukanth/afwall/blob/724c30ac369bb8fcb0d29bf36920b52c609374d0/aFWall/src/main/java/dev/ukanth/ufirewall/InterfaceTracker.java#L68.

But it doesn't work for bluetooth.

There is other way to get this. Using output of the command cat /proc/sys/net/ipv4/ip_forward is one of the indicator if tethering is enabled on any interface (USB, Bluetooth,...). 1 = tether and 0 = nontether.

Is it possible to implement this using the same InterfaceTracker (using root shell ?)

**Comment by n90p** [comment]
> Using output of the command cat /proc/sys/net/ipv4/ip_forward is one of the indicator if tethering is enabled on any interface (USB, Bluetooth,...). 1 = tether and 0 = nontether.

It's always 1 on my device


> Is it possible to implement this using the same InterfaceTracker

Yes, I've implemented getBluetoothTetherStatus. Works fine on my phone

**Comment by ukanth** [comment]
> > Using output of the command cat /proc/sys/net/ipv4/ip_forward is one of the indicator if tethering is enabled on any interface (USB, Bluetooth,...). 1 = tether and 0 = nontether.
> 
> It's always 1 on my device
> 
> > Is it possible to implement this using the same InterfaceTracker
> 
> Yes, I've implemented getBluetoothTetherStatus. Works fine on my phone

Cool, It might be only for v4. I will check it. Thanks !

**Comment by ukanth** [comment]
Have you tried using AFWall with bluetooth tether before this ? what was the issue without separate filter ?

**Comment by n90p** [comment]
> Have you tried using AFWall with bluetooth tether before this ? what was the issue without separate filter ?

I connected my phone to my tablet which shares internet via bluetooth tethering, and there are no way to block apps, all have free internet access
So I've added this feature

And I think that enableBluetooth() property and associated menu entry can be omitted

**Comment by ukanth** [comment]
Thanks. Are you going to update the code to reflect the changes related to enableBluetooth.?

**Comment by n90p** [comment]
Removed `Bluetooth control` entry from preferences, changed legend

**Comment by ukanth** [comment]
Im confused. If you want to implement fine grin control for tether, then it should be optional (like you did previously with preference), but not limited to just bluetooth. You may want to call tether (bluetooth & USB). Depending upon the tether type, we need to allow/deny traffic by updating rules.

Thanks.

**Comment by n90p** [comment]
That's not for tethering. That's for connectivity. Together with wifi/3g we have bluetooth network connectivity.

**Comment by ukanth** [comment]
Then call it tether connectivity. I would like to still keep that optional using preferences. Because by default most of the users does not use tether connectivity and should be optional.

**Pull request merged**
